mainText=While we work hard to keep the program suite stable and running smoothly, things can still go wrong. Because \
  this is a \
  volunteer project without the funding or team for large-scale testing, we rely on players to report any issues they \
  find. To do this, follow these steps:</p><blockquote><b>\
  1)</b> Save your game, campaign or unit. \
  Best make a ZIP of it so you can upload it with the issue report. \
  <br><b>\
  2) (Optional)</b> If you are on our Discord, \
  it can help to ask whether the bug has \
  already been reported. This may save you the effort of opening a report that ends up closed because the issue was \
  already fixed. Duplicate reports are fine. We just want to save you time. Not a member of our Discord community? \
  Consider pressing the 'Discord' button to join.<br><b>\
  3)</b> Press the appropriate button for the type of issue. \
  You will need a GitHub account. We used to allow anonymous reporting, but it caused problems and had to be removed\
  .<br><b>\
  4)</b> Fill out the issue report form, then upload the ZIP you created in step 1.</blockquote>
secondaryText=<h3 style="text-align:center">Which Bug Goes Where?</h3>\
  <ul>\
  <li>My bug was found during a scenario (i.e., a battle): <b>MegaMek</b> (ideally, we will need a save from before \
  the scenario started)\
  <li>My bug was found during unit customization: <b>MegaMekLab</b>\
  <li>My bug was found in campaign management: <b>MekHQ</b>\
  <li>I think a unit, planet, or other data is wrong: <b>Data</b>\
  <li>I'm not sure: <b>MegaMek</b> (don't worry, we'll sort it out)\
  </ul>
discord.text=Join our Discord
mm.text=MegaMek
mml.text=MegaMekLab
mhq.text=MekHQ
mmData.text=Data
